server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - profile
              - email

            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

            client-name: Google
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  application:
    name: MOAMOA_Backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity: 3600000
  refresh-token-validity: 1209600000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

aws:
  region: ap-northeast-2
  s3:
    bucket: moamoa-s3-prod-bucket
    public-base-url: https://moamoa-s3-prod-bucket.s3.ap-northeast-2.amazonaws.com
